### ISSUE TITLE
How to use that data from C?

### ISSUE THREAD

**Issue by alejandro-colomar** [Shreeshrii/tessdata_shreetest#2]
Could you please explain a little how should I use this data from the C API of Tesseract?

Until now I was doing this for the english default data (eng.traineddata):

`TessBaseAPIInit2(handle_ocr, NULL, "eng", OEM_LSTM_ONLY);`

Should I assume that I should do the following (for digits.traineddata)?:

`TessBaseAPIInit2(handle_ocr, NULL, "digits", OEM_LSTM_ONLY);`

Or should I do something else?

**Comment by Shreeshrii** [comment]
Yes, that should work. Please put in same location/folder as the eng.traineddata.

**Comment by AlejandroColomar** [comment]
Thank you very much!! It worked!!

It has some trouble with the punctuation, but it's not very important for me.  I'm reading prices, and I can assume that there are going to be always two decimal positions.

However I can give you the images I'm reading if they help your data be more accurate in the future :)

I don't know the font of my data.

**Comment by Shreeshrii** [comment]
I do not use this traineddata. It is only as a sample for trying out. 

You can provide a couple of images. I can use them for testing, or try to find a font similar to that to include in a future run.

**Comment by AlejandroColomar** [comment]
Just removing the `€` from the images gives a 100% accuracy :)
